### ISSUE TITLE
two (possibly) unrelated bugs

### ISSUE THREAD

**Issue by berithi** [VH-Lab/vhlab_vhtools#1]
bug #1 When I try to do VF with the graphical interface it gives me the following error: Warning: Negative data ignored 
> In axis>LocGetLimits (line 191)
  In axis (line 77)
  In at_roi_volumefilter (line 79)
  In at_roi_volumefilter (line 27)
  In at_itemeditlist_gui (line 363)
  In callbacknametag (line 14) 
Warning: Negative limits ignored 
> In ylabel (line 39)
  In at_roi_volumefilter (line 82)
  In at_roi_volumefilter (line 27)
  In at_itemeditlist_gui (line 363)
  In callbacknametag (line 14) 

I don't think it actually prevents it from working though. 

bug #2 When I look at the resulting file the info box shows me the info of another file, including for the CLA files...

**Comment by stevevanhooser** [comment]
This is not an issue with this package, i'll repost it in vhlab_mlapp_ArrayTomography
